services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/docker-go-cards"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - db
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL: disable
    networks:
      - backend

  testing:
    build:
      context: .
      dockerfile: Dockerfile
    command: "go test -v"
    ports:
      - "8081:8081"
    depends_on: 
      - db-test
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_HOST: db-test
      DB_PORT: 5432
      DB_SSL: disable
    networks:
      - backend-test

  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432" # I'm using that port for my localdb
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - backend

  db-test:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
      - backend-test

volumes:
  db:
    driver: local

networks:
  backend:
  backend-test:
